"""User-facing strings for Cinema Player."""

LANGUAGES = {
    "en": "English",
    "de": "Deutsch",
}

DEFAULT_LANGUAGE = "en"

STRINGS = {
    "en": {
        "theme_to_light": "light design",
        "theme_to_dark": "dark design",
        "playlist": "Playlist",
        "projection_zoom": "Projection zoom",
        "autoplay_delay": "Autoplay delay:",
        "seconds_short": "s",
        "idle_media": "Idle media:",
        "idle_none": "none",
        "beamer_status": "Beamer status",
        "beamer_output": "Output:",
        "beamer_output_busy": "Stop playback before changing the projector output.",
        "preview": "Preview",
        "no_program": "No program",
        "no_clip": "No clip",
        "live": "Live",
        "preview_mode": "Preview",
        "length_empty": "Length: --:--",
        "length_clip": "Length: {duration}   {container} - {video} / {audio} - {aspect}  PAR {pixel_aspect}",
        "still_image": "Still image   {container} - {width}x{height} - {aspect}  PAR {pixel_aspect}",
        "in_mark": "In",
        "out_mark": "Out",
        "in_value": "In: {value}",
        "out_value": "Out: {value}",
        "time_value": "Time: {value}",
        "total": "Total",
        "elapsed": "Elapsed",
        "remaining": "Remaining",
        "end": "End",
        "stop": "Stop",
        "pause": "Pause",
        "still": "Still",
        "start": "Start",
        "resume": "Resume",
        "set_in": "Set In",
        "set_out": "Set Out",
        "clear_in_out": "Clear In/Out",
        "rev": "rev",
        "play": "play",
        "fwd": "fwd",
        "import": "import",
        "new": "new",
        "load": "load",
        "save": "save",
        "refresh": "refresh",
        "refresh_playlist": "Refresh playlist",
        "reset_played": "reset played",
        "autoplay": "Autoplay",
        "played": "Played",
        "audio_track": "Audio track:",
        "subtitle": "Subtitle:",
        "display_time": "Display time:",
        "display_time_hint": "s   (0 = until resume)",
        "volume": "Volume",
        "save_volume": "Save volume",
        "video_preview": "video preview",
        "preview_unavailable": "Preview unavailable\n{error}",
        "ok": "OK",
        "mismatch": "Mismatch",
        "set_program": "Set program",
        "toggle_autoplay": "Toggle autoplay",
        "relink_entry": "Relink",
        "delete_entry": "Delete entry",
        "import_media": "Import media",
        "new_playlist": "New playlist",
        "new_playlist_title": "New playlist",
        "new_playlist_message": "Delete all playlist entries and start a new playlist?",
        "import_directory": "Import directory",
        "media_files": "Media",
        "all_files": "All files",
        "playlist_files": "Playlist",
        "import_error": "Import",
        "load_playlist": "Load playlist",
        "missing_badge": "MISSING",
        "missing_file": "Missing file: {path}",
        "missing_playlist": "{count} missing file(s) will be skipped during the program.",
        "missing_playback": "No playable files remain in the playlist.",
        "save_playlist": "Save playlist",
        "idle_screen_media": "Idle screen media",
        "projection_zoom_title": "Projection zoom",
        "projection_zoom_message": (
            "{filename} needs a zoom / aspect change ({aspect}, PAR {pixel_aspect}).\n"
            "Confirm after the projector zoom has been set."
        ),
        "playback": "Playback",
        "output_failed": "The video output could not be opened.",
        "pause_title": "Pause",
        "pause_message": "Pause playback? The projector output will go black.",
        "still_title": "Still",
        "still_message": "Freeze the current frame on the projector?",
        "stop_title": "Stop",
        "stop_clip": "Stop the current clip?",
        "stop_program": "Stop the program?",
        "state_off": "OFF",
        "state_program": "PROGRAM",
        "state_playing": "PLAYING",
        "until_resume": "resume",
        "auto_badge": "AUTO",
    },
    "de": {
        "theme_to_light": "helles Design",
        "theme_to_dark": "dunkles Design",
        "playlist": "Playlist",
        "projection_zoom": "Projektionszoom",
        "autoplay_delay": "Autoplay-Pause:",
        "seconds_short": "s",
        "idle_media": "Pausenmedium:",
        "idle_none": "keins",
        "beamer_status": "Beamer-Status",
        "beamer_output": "Ausgang:",
        "beamer_output_busy": "Wiedergabe beenden, bevor der Beamerausgang gewechselt wird.",
        "preview": "Vorschau",
        "no_program": "Kein Programm",
        "no_clip": "Kein Clip",
        "live": "Live",
        "preview_mode": "Vorschau",
        "length_empty": "Länge: --:--",
        "length_clip": "Länge: {duration}   {container} - {video} / {audio} - {aspect}  PAR {pixel_aspect}",
        "still_image": "Standbild   {container} - {width}x{height} - {aspect}  PAR {pixel_aspect}",
        "in_mark": "In",
        "out_mark": "Out",
        "in_value": "In: {value}",
        "out_value": "Out: {value}",
        "time_value": "Zeit: {value}",
        "total": "Gesamt",
        "elapsed": "Gelaufen",
        "remaining": "Rest",
        "end": "Ende",
        "stop": "Stop",
        "pause": "Pause",
        "still": "Standbild",
        "start": "Start",
        "resume": "Weiter",
        "set_in": "In setzen",
        "set_out": "Out setzen",
        "clear_in_out": "In/Out löschen",
        "rev": "Zurück",
        "play": "Play",
        "fwd": "Vor",
        "import": "importieren",
        "new": "neu",
        "load": "laden",
        "save": "speichern",
        "refresh": "aktualisieren",
        "refresh_playlist": "Playlist aktualisieren",
        "reset_played": "gespielte zurücksetzen",
        "autoplay": "Autoplay",
        "played": "Gespielt",
        "audio_track": "Tonspur:",
        "subtitle": "Untertitel:",
        "display_time": "Anzeigezeit:",
        "display_time_hint": "s   (0 = bis Weiter)",
        "volume": "Lautstärke",
        "save_volume": "Lautstärke speichern",
        "video_preview": "Videovorschau",
        "preview_unavailable": "Vorschau nicht verfügbar\n{error}",
        "ok": "OK",
        "mismatch": "Abweichung",
        "set_program": "Programm setzen",
        "toggle_autoplay": "Autoplay umschalten",
        "relink_entry": "Neu verknüpfen",
        "delete_entry": "Eintrag löschen",
        "import_media": "Medien importieren",
        "new_playlist": "Neue Playlist",
        "new_playlist_title": "Neue Playlist",
        "new_playlist_message": "Alle Playlist-Einträge löschen und eine neue Playlist beginnen?",
        "import_directory": "Ordner importieren",
        "media_files": "Medien",
        "all_files": "Alle Dateien",
        "playlist_files": "Playlist",
        "import_error": "Import",
        "load_playlist": "Playlist laden",
        "missing_badge": "FEHLT",
        "missing_file": "Datei fehlt: {path}",
        "missing_playlist": "{count} fehlende Datei(en) werden im Programm übersprungen.",
        "missing_playback": "In der Playlist sind keine abspielbaren Dateien mehr.",
        "save_playlist": "Playlist speichern",
        "idle_screen_media": "Pausenmedium",
        "projection_zoom_title": "Projektionszoom",
        "projection_zoom_message": (
            "{filename} erfordert eine Zoom- oder Seitenverhältnisänderung ({aspect}, PAR {pixel_aspect}).\n"
            "Bestätigen, nachdem der Beamerzoom eingestellt wurde."
        ),
        "playback": "Wiedergabe",
        "output_failed": "Der Videoausgang konnte nicht geöffnet werden.",
        "pause_title": "Pause",
        "pause_message": "Wiedergabe pausieren? Die Beamerausgabe wird schwarz.",
        "still_title": "Standbild",
        "still_message": "Aktuelles Bild auf dem Beamer einfrieren?",
        "stop_title": "Stop",
        "stop_clip": "Aktuellen Clip stoppen?",
        "stop_program": "Das Programm stoppen?",
        "state_off": "AUS",
        "state_program": "PROGRAMM",
        "state_playing": "WIEDERGABE",
        "until_resume": "weiter",
        "auto_badge": "AUTO",
    },
}

_language = DEFAULT_LANGUAGE


def set_language(code):
    global _language
    _language = code if code in STRINGS else DEFAULT_LANGUAGE
    return _language


def current_language():
    return _language


def t(key, **kwargs):
    table = STRINGS.get(_language) or STRINGS[DEFAULT_LANGUAGE]
    text = table.get(key) or STRINGS[DEFAULT_LANGUAGE].get(key) or key
    if kwargs:
        return text.format(**kwargs)
    return text
