"""User-facing strings for Cinema Player."""

LANGUAGES = {
    "en": "English",
    "de": "Deutsch",
}

DEFAULT_LANGUAGE = "en"

STRINGS = {
    "en": {
        "theme_to_light": "Light design",
        "theme_to_dark": "Dark design",
        "window_fullscreen": "Fullscreen",
        "language": "Language",
        "app_menu": "Settings",
        "calibration": "Calibration",
        "calibration_video": "Video",
        "calibration_audio": "Audio",
        "calibration_load_all": "Load all files",
        "media_directories": "Media directories",
        "remote_control": "Remote control",
        "remote_control_hint": (
            "Scan the QR code with a smartphone camera, or open one of the addresses. "
            "The link includes the token. Resume, Pause, Still, Stop, volume, "
            "and the program pointer are on the phone page."
        ),
        "remote_control_enable": "Enable network API",
        "remote_control_port": "Port",
        "remote_control_token": "Token *",
        "remote_control_token_required": "A token is required before remote control can be switched on.",
        "remote_control_urls": "Phone URL",
        "remote_control_qr": "QR code",
        "remote_control_qr_off": "No QR code while the API is off.",
        "remote_control_apply": "Apply",
        "remote_control_close": "Close",
        "remote_control_off": "The network API is switched off.",
        "media_directories_hint": "These folders are offered when media is imported into the playlist.",
        "media_directories_add": "Add",
        "media_directories_remove": "Remove",
        "media_directories_close": "Close",
        "media_directories_missing": "missing",
        "media_directories_choose": "Choose media folder",
        "media_directories_other": "Other location…",
        "media_directories_import_files": "Import files",
        "media_directories_import_folder": "Import folder",
        "copy_files": "Copy files",
        "copy_files_none": "choose…",
        "copy_files_choose": "Copy destination",
        "copy_files_missing": "Choose a folder before copying imported files.",
        "copy_files_failed": "The file could not be copied:\n{path}\n{error}",
        "copy_files_progress": "Copying {current} of {total}",
        "copy_files_progress_size": "{done} / {total}",
        "manual": "Operator manual",
        "manual_missing": "The operator manual was not found.",
        "quit": "Quit",
        "quit_busy": "Stop the program before quitting Cinema Player.",
        "playlist": "Playlist",
        "projection_zoom": "Beamer settingschange",
        "autoplay_delay": "Black-Pause:",
        "seconds_short": "s",
        "idle_media": "Idle media:",
        "idle_none": "none",
        "default_idle_media": "Use default Idle Media",
        "default_idle_media_missing": "The idle folder was not found.",
        "default_idle_media_empty": "No media was found in the idle folder.",
        "beamer_status": "Beamer status",
        "beamer_output": "Beamer output",
        "beamer_output_busy": "Stop playback before changing the projector output.",
        "edid": "EDID",
        "edid_title": "EDID — {output}",
        "edid_no_output": "No projector output is selected.",
        "edid_unavailable": "No EDID data was found for {output}.",
        "edid_output": "Output: {output}",
        "edid_source": "Source: {source}",
        "edid_size": "{bytes} bytes, {blocks} EDID block(s)",
        "edid_close": "Close",
        "beamer_test": "Beamer test image",
        "beamer_test_active": "The beamer test image is active.\nClose this window to end it.",
        "beamer_test_missing": "The Cinema Player logo file was not found.",
        "beamer_rates": "Rates: {rates}",
        "beamer_resolutions": "Resolutions: {resolutions}",
        "beamer_aspect": "Aspect ratio",
        "beamer_device": "Device",
        "preview": "Preview",
        "no_program": "program not started",
        "no_clip": "No clip",
        "live": "Live",
        "preview_mode": "Preview",
        "length_empty": "Length: --:--",
        "length_clip": "Length: {duration}   {container} - {video} / {audio} - {aspect}  PAR {pixel_aspect}  {colorspace}",
        "still_image": "Still image   {container} - {width}x{height} - {aspect}  PAR {pixel_aspect}  {colorspace}",
        "in_mark": "In",
        "out_mark": "Out",
        "in_value": "In: {value}",
        "out_value": "Out: {value}",
        "time_value": "Time: {value}",
        "total": "Total",
        "elapsed": "Elapsed",
        "remaining": "Remaining",
        "end": "End",
        "stop": "Stop",
        "pause": "Pause",
        "still": "Still",
        "start": "Start",
        "resume": "Resume",
        "set_in": "Set In",
        "set_out": "Set Out",
        "clear_in_out": "Clear In/Out",
        "rev": "rev",
        "play": "play",
        "fwd": "fwd",
        "import": "import",
        "new": "new",
        "load": "load",
        "save": "save",
        "refresh": "refresh",
        "refresh_playlist": "Check video files",
        "playlist_menu": "Playlist menu",
        "reset_played": "Reset playlist",
        "reset_played_title": "Reset playlist",
        "reset_played_message": (
            "Clear played flags and move the program pointer to the first entry?"
        ),
        "autosave_program_change": "Autosave at program change",
        "load_last_playlist_at_start": "Load last playlist at start",
        "analyze_loudness": "Analyze loudness",
        "analyze_loudness_title": "Analyze loudness",
        "analyze_loudness_message": (
            "ffmpeg will measure the loudness of every video in the playlist.\n"
            "This can take a while. Continue?"
        ),
        "analyze_loudness_busy": "Stop the program before analyzing loudness.",
        "analyze_loudness_none": "There are no videos to analyze.",
        "analyze_loudness_missing_ffmpeg": "ffmpeg was not found.",
        "autoplay": "Autoplay",
        "loop": "Loop",
        "played": "played",
        "audio_track": "Audio track:",
        "subtitle": "Subtitle:",
        "display_time": "Display time:",
        "display_time_hint": "s   (0 = until resume)",
        "volume": "Volume",
        "save_volume": "Save volume",
        "video_preview": "video preview",
        "preview_unavailable": "Preview unavailable\n{error}",
        "ok": "OK",
        "mismatch": "Mismatch",
        "set_program": "Set program pointer",
        "toggle_autoplay": "Toggle autoplay",
        "toggle_loop": "Toggle loop",
        "relink_entry": "Relink",
        "delete_entry": "Delete entry",
        "import_media": "Import media",
        "new_playlist": "New playlist",
        "new_playlist_title": "New playlist",
        "new_playlist_message": "Delete all playlist entries and start a new playlist?",
        "state_video_calibration": "Video calibration",
        "state_audio_calibration": "Audio calibration",
        "calibration_video_warning": (
            "Video calibration replaces the current playlist with the files from testdata/videotestdata.\n"
            "Continue?"
        ),
        "calibration_video_missing": "The testdata/videotestdata folder was not found.",
        "calibration_video_empty": "No videos were found in testdata/videotestdata.",
        "calibration_video_stop": "Leave video calibration and delete the test playlist?",
        "calibration_playlist_warning": (
            "{mode} replaces the current playlist with {name}.\nContinue?"
        ),
        "calibration_playlist_empty": "No videos were found in {name}.",
        "calibration_playlist_error": "The playlist {name} could not be read.\n{error}",
        "audiosync": "Audio calibration",
        "calibration_audio_warning": (
            "Audio calibration replaces the current playlist with the files from testdata/audiosyncdata.\n"
            "Continue?"
        ),
        "calibration_audio_missing": "The testdata/audiosyncdata folder was not found.",
        "calibration_audio_empty": "No videos were found in testdata/audiosyncdata.",
        "calibration_audio_stop": "Leave audio calibration and delete the test playlist?",
        "audiosync_delay": "A/V delay:",
        "audiosync_list": "Delays",
        "audiosync_load": "Load",
        "audiosync_save": "Save",
        "audiosync_list_title": "Audio calibration delays",
        "audiosync_list_empty": "No delays have been stored yet.",
        "audiosync_list_row": "{format}   {delay}",
        "audiosync_load_title": "Load audio calibration delays",
        "audiosync_save_title": "Save audio calibration delays",
        "audiosync_load_error": "The delay file could not be read.",
        "audiosync_save_error": "The delay file could not be written.\n{error}",
        "import_directory": "Import directory",
        "media_files": "Media",
        "all_files": "All files",
        "playlist_files": "Playlist",
        "import_error": "Import",
        "load_playlist": "Load playlist",
        "missing_badge": "MISSING",
        "missing_file": "Missing file: {path}",
        "missing_playlist": "{count} missing file(s) will be skipped during the program.",
        "missing_playback": "No playable files remain in the playlist.",
        "save_playlist": "Save playlist",
        "idle_screen_media": "Idle screen media",
        "projection_zoom_title": "Beamer settingschange",
        "projection_zoom_message": (
            "{filename} needs a beamer settings change\n(Aspect {aspect}, Pixel Aspect Ratio {pixel_aspect}, Colorspace {colorspace}).\n"
            "Confirm after the beamer has been set."
        ),
        "playback": "Playback",
        "output_failed": "The video output could not be opened.",
        "beamer_no_output_title": "No projector output",
        "beamer_no_output": (
            "No dedicated display was found for the projector.\n"
            "Connect a second output and choose it under Beamer output."
        ),
        "pause_title": "Pause",
        "pause_message": "Pause playback? The projector output will go black.",
        "still_title": "Still",
        "still_message": "Freeze the current frame on the projector?",
        "stop_title": "Stop",
        "stop_clip": "Stop the current clip?",
        "stop_program": "Stop the program?",
        "state_off": "OFF",
        "state_program": "PROGRAM",
        "state_playing": "PLAYING",
        "until_resume": "resume",
        "auto_badge": "AUTO",
        "loop_badge": "LOOP",
    },
    "de": {
        "theme_to_light": "helles Design",
        "theme_to_dark": "dunkles Design",
        "window_fullscreen": "Vollbildmodus",
        "language": "Sprache",
        "app_menu": "Einstellungen",
        "calibration": "Kalibrierung",
        "calibration_video": "Video",
        "calibration_audio": "Audio",
        "calibration_load_all": "Alle Files laden",
        "media_directories": "Medienverzeichnisse",
        "remote_control": "Fernsteuerung",
        "remote_control_hint": (
            "Scannen Sie den QR-Code mit der Smartphone-Kamera, oder öffnen Sie eine der Adressen. "
            "Der Link enthält das Token. Weiter, Pause, Standbild, Stop, Lautstärke "
            "und der Programmzeiger sind auf der Telefonseite."
        ),
        "remote_control_enable": "Netzwerk-API einschalten",
        "remote_control_port": "Port",
        "remote_control_token": "Token *",
        "remote_control_token_required": "Ein Token ist nötig, bevor die Fernsteuerung eingeschaltet werden kann.",
        "remote_control_urls": "Telefon-URL",
        "remote_control_qr": "QR-Code",
        "remote_control_qr_off": "Kein QR-Code, solange die API aus ist.",
        "remote_control_apply": "Übernehmen",
        "remote_control_close": "Schließen",
        "remote_control_off": "Die Netzwerk-API ist ausgeschaltet.",
        "media_directories_hint": "Diese Ordner stehen beim Laden von Medien in die Playlist zur Verfügung.",
        "media_directories_add": "Hinzufügen",
        "media_directories_remove": "Entfernen",
        "media_directories_close": "Schließen",
        "media_directories_missing": "fehlt",
        "media_directories_choose": "Medienordner wählen",
        "media_directories_other": "Anderer Speicherort…",
        "media_directories_import_files": "Dateien importieren",
        "media_directories_import_folder": "Ordner importieren",
        "copy_files": "Files kopieren",
        "copy_files_none": "wählen…",
        "copy_files_choose": "Kopierziel",
        "copy_files_missing": "Vor dem Kopieren muss ein Ordner gewählt sein.",
        "copy_files_failed": "Die Datei konnte nicht kopiert werden:\n{path}\n{error}",
        "copy_files_progress": "Kopiere {current} von {total}",
        "copy_files_progress_size": "{done} / {total}",
        "manual": "Bedienungsanleitung",
        "manual_missing": "Die Bedienungsanleitung wurde nicht gefunden.",
        "quit": "Beenden",
        "quit_busy": "Das Programm muss gestoppt sein, bevor Cinema Player beendet wird.",
        "playlist": "Playlist",
        "projection_zoom": "Einstellungswechsel",
        "autoplay_delay": "Schwarzpause:",
        "seconds_short": "s",
        "idle_media": "Pausenmedium:",
        "idle_none": "keins",
        "default_idle_media": "Standard-Pausenmedium verwenden",
        "default_idle_media_missing": "Der Ordner idle wurde nicht gefunden.",
        "default_idle_media_empty": "Im Ordner idle wurde kein Medium gefunden.",
        "beamer_status": "Beamer-Status",
        "beamer_output": "Beamerausgang",
        "beamer_output_busy": "Wiedergabe beenden, bevor der Beamerausgang gewechselt wird.",
        "edid": "EDID",
        "edid_title": "EDID — {output}",
        "edid_no_output": "Es ist kein Beamerausgang ausgewählt.",
        "edid_unavailable": "Für {output} wurden keine EDID-Daten gefunden.",
        "edid_output": "Ausgang: {output}",
        "edid_source": "Quelle: {source}",
        "edid_size": "{bytes} Byte, {blocks} EDID-Block(s)",
        "edid_close": "Schließen",
        "beamer_test": "Beamer-Testbild",
        "beamer_test_active": "Das Beamer-Testbild ist aktiv.\nDieses Fenster schließen, um es zu beenden.",
        "beamer_test_missing": "Die Cinema-Player-Logo-Datei wurde nicht gefunden.",
        "beamer_rates": "Frequenzen: {rates}",
        "beamer_resolutions": "Auflösungen: {resolutions}",
        "beamer_aspect": "Seitenverhältnis",
        "beamer_device": "Gerät",
        "preview": "Vorschau",
        "no_program": "Programm nicht gestartet",
        "no_clip": "Kein Clip",
        "live": "Live",
        "preview_mode": "Vorschau",
        "length_empty": "Länge: --:--",
        "length_clip": "Länge: {duration}   {container} - {video} / {audio} - {aspect}  PAR {pixel_aspect}  {colorspace}",
        "still_image": "Standbild   {container} - {width}x{height} - {aspect}  PAR {pixel_aspect}  {colorspace}",
        "in_mark": "In",
        "out_mark": "Out",
        "in_value": "In: {value}",
        "out_value": "Out: {value}",
        "time_value": "Zeit: {value}",
        "total": "Gesamt",
        "elapsed": "Gelaufen",
        "remaining": "Rest",
        "end": "Ende",
        "stop": "Stop",
        "pause": "Pause",
        "still": "Standbild",
        "start": "Start",
        "resume": "Weiter",
        "set_in": "In setzen",
        "set_out": "Out setzen",
        "clear_in_out": "In/Out löschen",
        "rev": "Zurück",
        "play": "Play",
        "fwd": "Vor",
        "import": "importieren",
        "new": "neu",
        "load": "laden",
        "save": "speichern",
        "refresh": "aktualisieren",
        "refresh_playlist": "Videofiles prüfen",
        "playlist_menu": "Playlist-Menü",
        "reset_played": "Playlist zurücksetzen",
        "reset_played_title": "Playlist zurücksetzen",
        "reset_played_message": (
            "Gespielte Markierungen löschen und den Programmzeiger auf den ersten Eintrag setzen?"
        ),
        "autosave_program_change": "Autosave bei Programmwechsel",
        "load_last_playlist_at_start": "Letzte Playlist beim Start laden",
        "analyze_loudness": "Lautheit analysieren",
        "analyze_loudness_title": "Lautheit analysieren",
        "analyze_loudness_message": (
            "ffmpeg misst die Lautheit aller Videos in der Playlist.\n"
            "Das kann eine Weile dauern. Fortfahren?"
        ),
        "analyze_loudness_busy": "Das Programm muss gestoppt sein, bevor die Lautheit analysiert wird.",
        "analyze_loudness_none": "Es gibt keine Videos zum Analysieren.",
        "analyze_loudness_missing_ffmpeg": "ffmpeg wurde nicht gefunden.",
        "autoplay": "Autoplay",
        "loop": "Loop",
        "played": "gespielt",
        "audio_track": "Tonspur:",
        "subtitle": "Untertitel:",
        "display_time": "Anzeigezeit:",
        "display_time_hint": "s   (0 = bis Weiter)",
        "volume": "Lautstärke",
        "save_volume": "Lautstärke speichern",
        "video_preview": "Videovorschau",
        "preview_unavailable": "Vorschau nicht verfügbar\n{error}",
        "ok": "OK",
        "mismatch": "Abweichung",
        "set_program": "Programmzeiger setzen",
        "toggle_autoplay": "Autoplay umschalten",
        "toggle_loop": "Loop umschalten",
        "relink_entry": "Neu verknüpfen",
        "delete_entry": "Eintrag löschen",
        "import_media": "Medien importieren",
        "new_playlist": "Neue Playlist",
        "new_playlist_title": "Neue Playlist",
        "new_playlist_message": "Alle Playlist-Einträge löschen und eine neue Playlist beginnen?",
        "state_video_calibration": "Videokalibrierung",
        "state_audio_calibration": "Audiokalibrierung",
        "calibration_video_warning": (
            "Die Videokalibrierung ersetzt die aktuelle Playlist durch die Dateien aus testdata/videotestdata.\n"
            "Fortfahren?"
        ),
        "calibration_video_missing": "Der Ordner testdata/videotestdata wurde nicht gefunden.",
        "calibration_video_empty": "Im Ordner testdata/videotestdata wurden keine Videos gefunden.",
        "calibration_video_stop": "Videokalibrierung verlassen und die Test-Playlist löschen?",
        "calibration_playlist_warning": (
            "{mode} ersetzt die aktuelle Playlist durch {name}.\nFortfahren?"
        ),
        "calibration_playlist_empty": "In {name} wurden keine Videos gefunden.",
        "calibration_playlist_error": "Die Playlist {name} konnte nicht gelesen werden.\n{error}",
        "audiosync": "Audiokalibrierung",
        "calibration_audio_warning": (
            "Die Audiokalibrierung ersetzt die aktuelle Playlist durch die Dateien aus testdata/audiosyncdata.\n"
            "Fortfahren?"
        ),
        "calibration_audio_missing": "Der Ordner testdata/audiosyncdata wurde nicht gefunden.",
        "calibration_audio_empty": "Im Ordner testdata/audiosyncdata wurden keine Videos gefunden.",
        "calibration_audio_stop": "Audiokalibrierung verlassen und die Test-Playlist löschen?",
        "audiosync_delay": "A/V-Versatz:",
        "audiosync_list": "Delays",
        "audiosync_load": "Laden",
        "audiosync_save": "Speichern",
        "audiosync_list_title": "Audiokalibrierung-Delays",
        "audiosync_list_empty": "Es sind noch keine Delays gespeichert.",
        "audiosync_list_row": "{format}   {delay}",
        "audiosync_load_title": "Audiokalibrierung-Delays laden",
        "audiosync_save_title": "Audiokalibrierung-Delays speichern",
        "audiosync_load_error": "Die Delay-Datei konnte nicht gelesen werden.",
        "audiosync_save_error": "Die Delay-Datei konnte nicht geschrieben werden.\n{error}",
        "import_directory": "Ordner importieren",
        "media_files": "Medien",
        "all_files": "Alle Dateien",
        "playlist_files": "Playlist",
        "import_error": "Import",
        "load_playlist": "Playlist laden",
        "missing_badge": "FEHLT",
        "missing_file": "Datei fehlt: {path}",
        "missing_playlist": "{count} fehlende Datei(en) werden im Programm übersprungen.",
        "missing_playback": "In der Playlist sind keine abspielbaren Dateien mehr.",
        "save_playlist": "Playlist speichern",
        "idle_screen_media": "Pausenmedium",
        "projection_zoom_title": "Beamereinstellungswechsel",
        "projection_zoom_message": (
            "{filename} erfordert eine Änderung der Einstellungen am Beamer\n(Seitenverhältnis {aspect}, Pixelseitenverhältnis {pixel_aspect}, Farbraum {colorspace}).\n"
            "Bestätigen, nachdem der Beamer eingestellt wurde."
        ),
        "playback": "Wiedergabe",
        "output_failed": "Der Videoausgang konnte nicht geöffnet werden.",
        "beamer_no_output_title": "Kein Beamerausgang",
        "beamer_no_output": (
            "Es wurde kein eigener Bildschirm für den Beamer gefunden.\n"
            "Schließen Sie einen zweiten Ausgang an und wählen Sie ihn unter Beamerausgang."
        ),
        "pause_title": "Pause",
        "pause_message": "Wiedergabe pausieren? Die Beamerausgabe wird schwarz.",
        "still_title": "Standbild",
        "still_message": "Aktuelles Bild auf dem Beamer einfrieren?",
        "stop_title": "Stop",
        "stop_clip": "Aktuellen Clip stoppen?",
        "stop_program": "Das Programm stoppen?",
        "state_off": "AUS",
        "state_program": "PROGRAMM",
        "state_playing": "WIEDERGABE",
        "until_resume": "weiter",
        "auto_badge": "AUTO",
        "loop_badge": "LOOP",
    },
}

_language = DEFAULT_LANGUAGE


def set_language(code):
    global _language
    _language = code if code in STRINGS else DEFAULT_LANGUAGE
    return _language


def current_language():
    return _language


def t(key, **kwargs):
    table = STRINGS.get(_language) or STRINGS[DEFAULT_LANGUAGE]
    text = table.get(key) or STRINGS[DEFAULT_LANGUAGE].get(key) or key
    if kwargs:
        return text.format(**kwargs)
    return text
